version: "3.9"

networks:
  app_network:
    name: app.network
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: app.db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./source/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    command: ./main -memory=${MEMORY_MODE}
    depends_on:
      - postgres
    networks:
      - app_network
    ports:
      - "8080:8080"
    expose:
      - "8080"